# Generated by Django 2.1.12 on 2019-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20190914_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceset',
            name='correct_choice',
            field=models.IntegerField(),
        ),
    ]
