# Generated by Django 2.1.12 on 2019-09-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20190914_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='choiceset',
            name='question',
        ),
        migrations.DeleteModel(
            name='ChoiceSet',
        ),
    ]
