# Generated by Django 2.1.12 on 2019-09-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20190914_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
