# Generated by Django 2.1.12 on 2019-09-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20190916_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('choice_text1', models.CharField(max_length=200)),
                ('choice_text2', models.CharField(max_length=200)),
                ('choice_text3', models.CharField(max_length=200)),
                ('choice_text4', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Tag')),
            ],
        ),
    ]
