# Generated by Django 2.1.12 on 2019-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
