# Generated by Django 2.1.12 on 2019-09-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_individual_test_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(max_length=250)),
                ('correct_option', models.CharField(max_length=250)),
                ('College_Registration_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Tag')),
            ],
        ),
    ]
