# Generated by Django 2.1.12 on 2019-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_student_individual_test_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='First_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Login_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
