# Generated by Django 2.1.12 on 2019-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20190918_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Login_Count',
            field=models.BooleanField(default=0),
        ),
    ]
