# Generated by Django 2.1.12 on 2019-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_auto_20190919_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Login_Count',
            field=models.IntegerField(default=0),
        ),
    ]
