# Generated by Django 2.1.12 on 2019-09-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_auto_20190919_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Graduation_Year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone_Number',
            field=models.IntegerField(default=9876543210),
        ),
    ]
